import React,{useState} from 'react';
import {createRoot} from 'react-dom/client';
import {BrowserRouter,useNavigate} from 'react-router-dom';
import {api,saveSession,clearSession,sessionUser} from './services/api';
import './styles.css';

const roleHome=r=>r==='ADMIN'?'/admin':r==='OWNER'?'/owner':'/stores';
function App(){const [user,setUser]=useState(sessionUser());const nav=useNavigate();
 const login=async(e)=>{e.preventDefault();try{const f=new FormData(e.currentTarget);const d=await api.post('/auth/login',{email:f.get('email'),password:f.get('password')});saveSession(d.data);setUser(d.data.user);nav(roleHome(d.data.user.role));}catch(e){alert(e.response?.data?.message||'Login failed')}};
 const logout=()=>{clearSession();setUser(null);nav('/login')};
 if(!user)return <Auth login={login} onRegister={()=>nav('/register')}/>;
 return <Layout user={user} logout={logout}/>;
}
function Layout({user,logout}){const nav=useNavigate();const [page,setPage]=useState(location.pathname);const go=p=>{setPage(p);nav(p)};return <div className="app"><header><div className="brand">StoreRate</div><div className="userbar"><span>{user.name} · {user.role}</span><button className="ghost" onClick={logout}>Logout</button></div></header><main>{page==='/admin'?<Admin/>:page==='/owner'?<Owner/>:<Stores/>}</main></div>}
function Auth({login,onRegister}){return <div className="auth"><div className="auth-card"><h1>StoreRate</h1><p className="muted">Store rating management platform</p><form onSubmit={login}><label>Email<input name="email" type="email" required/></label><label>Password<input name="password" type="password" required/></label><button>Sign in</button></form><p>New user? <button className="link" onClick={onRegister}>Create an account</button></p><div className="demo"><b>Demo:</b> admin@example.com / Admin@123<br/>owner@example.com / Owner@123<br/>user@example.com / User@123</div></div></div>}
function Register(){const nav=useNavigate();const [loading,setLoading]=useState(false);async function submit(e){e.preventDefault();setLoading(true);try{const f=new FormData(e.currentTarget);const d=await api.post('/auth/register',Object.fromEntries(f));saveSession(d.data);nav('/stores')}catch(e){alert(e.response?.data?.message||'Registration failed')}finally{setLoading(false)}}return <div className="auth"><div className="auth-card"><h1>Create account</h1><form onSubmit={submit}><Field n="name" label="Full name"/><Field n="email" label="Email" type="email"/><Field n="address" label="Address"/><Field n="password" label="Password" type="password"/><button disabled={loading}>{loading?'Creating...':'Create account'}</button></form><p>Already registered? <button className="link" onClick={()=>nav('/login')}>Sign in</button></p></div></div>}
function Field({n,label,type='text',...p}){return <label>{label}<input name={n} type={type} required {...p}/></label>}
function Password(){const [msg,setMsg]=useState('');return <section className="card"><h2>Change password</h2><form className="inline-form" onSubmit={async e=>{e.preventDefault();const p=e.currentTarget.password.value;try{await api.put('/auth/password',{password:p});setMsg('Password updated.')}catch(e){setMsg(e.response?.data?.message||'Update failed')}}}><input name="password" type="password" placeholder="New password" required/><button>Update</button></form>{msg&&<p className="muted">{msg}</p>}</section>}
function Stores(){const [stores,setStores]=useState([]);const [search,setSearch]=useState('');const [sort,setSort]=useState('name');const [order,setOrder]=useState('asc');const [refresh,setRefresh]=useState(0);const user=sessionUser();React.useEffect(()=>{api.get('/stores',{params:{search,sort,order}}).then(r=>setStores(r.data.stores)).catch(e=>alert(e.response?.data?.message||'Could not load stores'))},[search,sort,order,refresh]);const rate=async(s)=>{const value=Number(prompt(`Enter rating for ${s.name} (1-5):`,s.user_rating||5));if(!Number.isInteger(value)||value<1||value>5)return;if(s.user_rating)await api.put(`/ratings/${s.id}`,{rating:value});else await api.post('/ratings',{storeId:s.id,rating:value});setRefresh(x=>x+1)};return <div className="stack"><section className="hero"><div><h1>Stores</h1><p>Search stores and manage your submitted ratings.</p></div></section><section className="card"><div className="toolbar"><input placeholder="Search name or address..." value={search} onChange={e=>setSearch(e.target.value)}/><select value={sort} onChange={e=>setSort(e.target.value)}><option value="name">Name</option><option value="address">Address</option><option value="rating">Rating</option></select><button className="ghost" onClick={()=>setOrder(order==='asc'?'desc':'asc')}>{order==='asc'?'↑ Asc':'↓ Desc'}</button></div><Table headers={['Store','Address','Overall','Your rating','Action']} rows={stores.map(s=>[<b>{s.name}</b>,s.address,`${s.overall_rating}/5`,s.user_rating?`${s.user_rating}/5`:'Not rated',<button onClick={()=>rate(s)}>{s.user_rating?'Modify':'Rate'}</button>])}/></section><Password/></div>}
function Table({headers,rows}){return <div className="table-wrap"><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.length?rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{c}</td>)}</tr>):<tr><td colSpan={headers.length} className="empty">No records found.</td></tr>}</tbody></table></div>}
function Admin(){const [stats,setStats]=useState({users:0,stores:0,ratings:0});const [users,setUsers]=useState([]);const [stores,setStores]=useState([]);const [tab,setTab]=useState('users');const [q,setQ]=useState('');const [sort,setSort]=useState('name');const [order,setOrder]=useState('asc');const load=async()=>{const [a,b,c]=await Promise.all([api.get('/admin/stats'),api.get('/admin/users',{params:{name:q,email:q,address:q,sort,order}}),api.get('/admin/stores',{params:{name:q,email:q,address:q,sort,order}})]);setStats(a.data);setUsers(b.data.users);setStores(c.data.stores)};React.useEffect(()=>{load().catch(e=>alert(e.response?.data?.message||'Admin load failed'))},[q,sort,order]);const addUser=async()=>{const name=prompt('Name (20-60 chars)');if(!name)return;const email=prompt('Email');const address=prompt('Address');const password=prompt('Password');const role=prompt('Role: ADMIN, USER or OWNER','USER');try{await api.post('/admin/users',{name,email,address,password,role});load()}catch(e){alert(e.response?.data?.message||'Could not create user')}};return <div className="stack"><section className="hero"><div><h1>Administrator dashboard</h1><p>Manage platform users, stores and ratings.</p></div><div style={{display:'flex',gap:'8px'}}><button onClick={addUser}>+ Add user</button><button className="ghost" onClick={async()=>{const name=prompt('Store name');if(!name)return;const email=prompt('Store email');const address=prompt('Store address');const ownerId=prompt('Owner user ID (optional)');try{await api.post('/stores',{name,email,address,ownerId:ownerId?Number(ownerId):null});load()}catch(e){alert(e.response?.data?.message||'Could not create store')}}}>+ Add store</button></div></section><div className="stats"><Stat n={stats.users} l="Users"/><Stat n={stats.stores} l="Stores"/><Stat n={stats.ratings} l="Ratings"/></div><section className="card"><div className="tabs"><button className={tab==='users'?'active':''} onClick={()=>setTab('users')}>Users</button><button className={tab==='stores'?'active':''} onClick={()=>setTab('stores')}>Stores</button></div><div className="toolbar"><input placeholder="Filter by name, email or address..." value={q} onChange={e=>setQ(e.target.value)}/><select value={sort} onChange={e=>setSort(e.target.value)}><option value="name">Name</option><option value="email">Email</option><option value="address">Address</option><option value="role">Role</option><option value="rating">Rating</option></select><button className="ghost" onClick={()=>setOrder(order==='asc'?'desc':'asc')}>{order==='asc'?'↑ Asc':'↓ Desc'}</button></div>{tab==='users'?<Table headers={['Name','Email','Address','Role']} rows={users.map(u=>[u.name,u.email,u.address,u.role])}/>:<Table headers={['Name','Email','Address','Rating']} rows={stores.map(s=>[s.name,s.email,s.address,`${s.overall_rating}/5`])}/>}</section></div>}
function Stat({n,l}){return <div className="stat"><strong>{n}</strong><span>{l}</span></div>}
function Owner(){const [data,setData]=useState(null);React.useEffect(()=>{api.get('/owner/dashboard').then(r=>setData(r.data)).catch(e=>alert(e.response?.data?.message||'Owner load failed'))},[]);return <div className="stack"><section className="hero"><div><h1>Store owner dashboard</h1><p>See who rated your store and your current average.</p></div></section>{data&&<><div className="stats"><Stat n={data.store.average_rating} l="Average rating"/><Stat n={data.store.rating_count} l="Submitted ratings"/></div><section className="card"><h2>{data.store.name}</h2><p className="muted">{data.store.address}</p><Table headers={['User','Email','Rating','Last updated']} rows={data.ratings.map(r=>[r.name,r.email,`${r.rating}/5`,new Date(r.updated_at).toLocaleString()])}/></section></>}<Password/></div>}
export {App,Register};
